from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class MessageObject(BaseModel):
    sender: str = Field(..., description="The sender of the message (scammer, agent, user)")
    text: str = Field(..., description="The content of the message")
    timestamp: int = Field(..., description="Epoch millisecond timestamp")

class MessageHistoryObject(BaseModel):
    sender: str
    text: str
    timestamp: Optional[int] = None

class SessionMetadata(BaseModel):
    channel: Optional[str] = Field(default="SMS", description="SMS, WhatsApp, Email, Chat, etc.")
    language: Optional[str] = Field(default="English")
    locale: Optional[str] = Field(default="IN")

class MessageEventRequest(BaseModel):
    sessionId: str = Field(..., alias="sessionId")
    message: MessageObject = Field(...)
    conversationHistory: List[MessageHistoryObject] = Field(default_factory=list, alias="conversationHistory")
    metadata: Optional[SessionMetadata] = Field(default_factory=SessionMetadata)

    # To allow using both field names and aliases during parsing
    class Config:
        populate_by_name = True

class MessageEventResponse(BaseModel):
    status: str = Field(default="success")
    reply: str = Field(..., description="Believable reply generated by the agent persona")

class ExtractedIntelligenceSchema(BaseModel):
    bankAccounts: List[str] = Field(default_factory=list, alias="bankAccounts")
    upiIds: List[str] = Field(default_factory=list, alias="upiIds")
    phishingLinks: List[str] = Field(default_factory=list, alias="phishingLinks")
    phoneNumbers: List[str] = Field(default_factory=list, alias="phoneNumbers")
    suspiciousKeywords: List[str] = Field(default_factory=list, alias="suspiciousKeywords")

    class Config:
        populate_by_name = True

class SessionReportResponse(BaseModel):
    sessionId: str = Field(..., alias="sessionId")
    scamDetected: bool = Field(..., alias="scamDetected")
    totalMessagesExchanged: int = Field(..., alias="totalMessagesExchanged")
    extractedIntelligence: ExtractedIntelligenceSchema = Field(..., alias="extractedIntelligence")
    agentNotes: str = Field(..., alias="agentNotes")

    class Config:
        populate_by_name = True
